CREATE TABLE CLIENTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CPF TEXT NOT NULL UNIQUE,
	ADDRESS TEXT NOT NULL,
	NEIGHBORHOOD TEXT NULL,
	CITY TEXT NOT NULL,
	TELEPHONE TEXT NULL,
	CELLPHONE TEXT NULL
);

CREATE TABLE PROVIDERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CNPJ TEXT NOT NULL UNIQUE,
	EMAIL TEXT NULL UNIQUE
);

CREATE TABLE PRODUCTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL UNIQUE,
	GROSS_PRICE REAL NOT NULL,
	NET_PRICE REAL NOT NULL,
	PROFIT_PERCENTAGE REAL NOT NULL,
	PROVIDER INTEGER,
	FOREIGN KEY (PROVIDER) REFERENCES PROVIDERS (ID)
);

CREATE TABLE SERVICES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL UNIQUE,
	PRICE REAL NOT NULL
);

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	ALIAS TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL
);
