CREATE TABLE PROVIDERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	CNPJ TEXT NOT NULL UNIQUE
);

CREATE TABLE PRODUCTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL UNIQUE,
	GROSS_PRICE REAL NOT NULL,
	NET_PRICE REAL NOT NULL,
	PROFIT_PERCENTAGE REAL NOT NULL,
	PROVIDER INTEGER,
	FOREIGN KEY (PROVIDER) REFERENCES PROVIDERS (ID)
);

CREATE TABLE USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME TEXT NOT NULL,
	USERNAME TEXT NOT NULL UNIQUE,
	PASSWORD TEXT NOT NULL
);
