<?php
//--// -------------- //--//
//--// UTIL FUNCTIONS //--//
//--// -------------- //--//

namespace api\util;

require_once __DIR__ . '/../config.php'; // CARREGA AS CONFIGURAÇÕES GLOBAIS (DEBUG)
require_once __DIR__ . '/../controllers/session.php'; // CARREGA O CONTROLADOR DE SESSÕES (GET)


/** ALTERA O CABEÇALHO DO DOCUMENTO PARA DEIXAR O TIPO DO CONTEÚDO COMO JSON
 * @return void
 */
function content(): void {
	// DEFINE O CONTEÚDO DA RESPOSTA (JSON)
	header('Content-Type: application/json; charset=utf-8');

	// DEFINE UMA DATA DE EXPIRAÇÃO DO CONTEÚDO (1 MÊS)
	$expirationDate = date_add(date_create(), date_interval_create_from_date_string('1 month'));
	header('Expires: ' . date_format($expirationDate, 'D, d M Y H:i:s \G\M\T'));

	// HABILITA O COMPARTILHAMENTO DE RECURSOS ENTRE DIFERENTES ORIGENS (CORS)
	header('Access-Control-Allow-Origin: *');
	header('Access-Control-Allow-Methods: GET, POST');
	header('Access-Control-Allow-Headers: X-Requested-With');
}


/** IMPRIME UM JSON E DEFINE O CÓDIGO DE RESPOSTA
 * @param int $status
 * @param bool $success
 * @param string $message
 * @param array<mixed> $data
 * @return bool
 */
function response(int $status=200, bool $success=true, string $message='', array $data=[]): bool {
	http_response_code($status);
	$success = $success && $status >= 400 ? false : $success;

	if(empty($message)) {
		$message = match($status) {
			200, 201, 204 => 'Sucesso.',
			400, 406 => 'Requisição mal formulada.',
			401, 403 => 'Usuário não autorizado.',
			404 => 'Registro não encontrado.',
			500 => 'Erro interno.',
			default => 'Resposta padrão da API.'
		};
	}

	echo json_encode([
		'status' => $status,
		'success' => $success,
		'message' => $message,
		'data' => $data,
		'error' => DEBUG ? error_get_last() : null,
		'history' => DEBUG ? \controller\session\get()['history'] : null
	]);

	unset($_SESSION['history']);

	return $success;
}


/** RETORNA O TIPO DE ERRO DE ACORDO COM O CÓDIGO
 * @param int $code
 * @return string
 */
function status(int $code): string {
	return match($code) {
		// RESPOSTAS DE INFORMAÇÃO
		100 => 'Continue', // TUDO OCORREU BEM ATÉ AGORA, O CLIENTE DEVE CONTINUAR COM A REQUISIÇÃO OU IGNORAR SE JÁ CONCLUIU
		101 => 'Switching Protocol', // O SERVIDOR ESTÁ ALTERANDO O PROTOCOLO
		103 => 'Early Hints', // O AGENTE DEVE INICIAR UM PRÉ-CARREGAMENTO, POIS O SERVIDOR PREPARA UMA RESPOSTA

		// RESPOSTAS DE SUCESSO
		200 => 'OK', // REQUISIÇÃO BEM SUCEDIDA
		201 => 'Created', // A REQUISIÇÃO FOI BEM SUCEDIDA E UM NOVO RECURSO FOI CRIADO COMO RESULTADO
		202 => 'Accepted', // A REQUISIÇÃO FOI RECEBIDA, MAS NENHUMA AÇÃO FOI TOMADA SOBRE ELA
		203 => 'Non-Authoritative Information', // O CONJUNTO DE META-INFORMAÇÕES RETORNADAS NÃO É O CONJUNTO EXATO DISPONÍVEL NO SERVIDOR DE ORIGEM, MAS COLETADO DE UMA CÓPIA LOCAL OU DE TERCEIROS
		204 => 'No Content', // NÃO HÁ CONTEÚDO PARA ENVIAR PARA ESTA SOLICITAÇÃO
		205 => 'Reset Content', // O SERVIDOR ATENDEU À SOLICITAÇÃO E DESEJA QUE O AGENTE DO USUÁRIO REDEFINA A "VISUALIZAÇÃO DO DOCUMENTO", QUE CAUSOU O ENVIO DA SOLICITAÇÃO, AO ESTADO ORIGINAL RECEBIDO DO SERVIDOR DE ORIGEM
		206 => 'Partial Content', // O CABEÇALHO DE INTERVALO ENVIADO PELO CLIENTE IRÁ SEPARAR O DOWNLOAD EM VÁRIOS FLUXOS

		// MENSAGENS DE REDIRECIONAMENTO
		300 => 'Multiple Choice', // A REQUISIÇÃO TEM MAIS DE UMA RESPOSTA POSSÍVEL
		301 => 'Moved Permanently', // A URI DO RECURSO REQUERIDO MUDOU
		302 => 'Found', // A URI DO RECURSO REQUERIDO FOI MUDADA TEMPORARIAMENTE
		303 => 'See Other', // O SERVIDOR MANDA ESSA RESPOSTA PARA INSTRUIR AO CLIENTE BUSCAR O RECURSO REQUISITADO EM OUTRA URI COM UMA REQUISIÇÃO GET
		304 => 'Not Modified', // DIZ AO CLIENTE QUE A RESPOSTA NÃO FOI MODIFICADA (ESSA RESPOSTA É USADA PARA QUESTÕES DE CACHE)
		307 => 'Temporary Redirect', // O SERVIDOR ENVIA ESTA RESPOSTA DIRECIONANDO O CLIENTE A BUSCAR O RECURSO REQUISITADO EM OUTRA URI COM O MESMO MÉTODO QUE FOI UTILIZADO NA REQUISIÇÃO ORIGINAL
		308 => 'Permanent Redirect', // O RECURSO ESTÁ PERMANENTEMENTE LOCALIZADO EM OUTRA URI, ESPECIFICADA PELO CABEÇALHO DE RESPOSTA "LOCATION"

		// RESPOSTAS DE ERRO DO CLIENTE
		400 => 'Bad Request', // O SERVIDOR NÃO ENTENDEU A SOLICITAÇÃO DEVIDO À SINTAXE INVÁLIDA
		401 => 'Unauthorized', // O CLIENTE DEVE SE AUTENTICAR PARA OBTER A RESPOSTA
		403 => 'Forbidden', // O CLIENTE NÃO POSSUI DIRETO DE ACESSO AO CONTEÚDO
		404 => 'Not Found', // NÃO ENCONTROU O RECURSO SOLICITADO
		405 => 'Method Not Allowed', // O MÉTODO DE SOLICITAÇÃO É CONHECIDO PELO SERVIDOR, MAS FOI DESATIVADO E NÃO PODE SER USADO
		406 => 'Not Acceptable', // NÃO ENCONTROU NENHUM CONTEÚDO QUE ESTEJA DE ACORDO COM OS CRITÉRIOS RECEBIDOS
		407 => 'Proxy Authentication Required', // SEMELHANTE AO 401, POREM É NECESSÁRIO QUE A AUTENTICAÇÃO SEJA FEITA POR UM PROXY
		408 => 'Request Timeout', // A CONEXÃO ESTÁ OCIOSA, MESMO SEM QUALQUER REQUISIÇÃO PRÉVIA PELO CLIENTE
		409 => 'Conflict', // A REQUISIÇÃO CONFLITOU COM O ESTADO ATUAL DO SERVIDOR
		410 => 'Gone', // O CONTEÚDO REQUISITADO FOI PERMANENTEMENTE DELETADO DO SERVIDOR, SEM NENHUM ENDEREÇO DE REDIRECIONAMENTO
		411 => 'Length Required', // O SERVIDOR REJEITOU A REQUISIÇÃO PORQUE O CAMPO "CONTENT-LENGTH" DO CABEÇALHO NÃO ESTÁ DEFINIDO E O SERVIDOR O REQUER
		412 => 'Precondition Failed', // O CLIENTE INDICOU NOS SEUS CABEÇALHOS PRÉ-CONDIÇÕES QUE O SERVIDOR NÃO ATENDE
		413 => 'Payload Too Large', // A REQUISIÇÃO É MAIOR QUE OS LIMITES DEFINIDOS PELO SERVIDOR
		414 => 'URI Too Long', // A URI REQUISITADA PELO CLIENTE É MAIOR QUE O SERVIDOR ACEITA PARA INTERPRETAR
		415 => 'Unsupported Media Type', // O FORMATO DE MÍDIA DOS DADOS REQUISITADOS NÃO É SUPORTADO PELO SERVIDOR
		416 => 'Requested Range Not Satisfiable', // O TRECHO ESPECIFICADO PELO CAMPO "RANGE" DO CABEÇALHO NA REQUISIÇÃO NÃO PODE SER PREENCHIDO (É POSSÍVEL QUE O TRECHO ESTEJA FORA DO TAMANHO DOS DADOS DA URI ALVO)
		417 => 'Expectation Failed', // A EXPECTATIVA INDICADA PELO CAMPO "EXPECT" DO CABEÇALHO DA REQUISIÇÃO NÃO PODE SER SATISFEITA PELO SERVIDOR
		418 => 'I\'m a teapot', // O SERVIDOR RECUSA A TENTATIVA DE COAR CAFÉ NUM BULE DE CHÁ
		422 => 'Unprocessable Entity', // A REQUISIÇÃO ESTÁ BEM FORMADA MAS INABILITADA PARA SER SEGUIDA DEVIDO AOS ERROS SEMÂNTICOS
		425 => 'Too Early', // O SERVIDOR NÃO ESTÁ DISPOSTO A ARRISCAR PROCESSAR UMA REQUISIÇÃO QUE PODE SER REFEITA
		426 => 'Upgrade Required', // O SERVIDOR SE RECUSA A EXECUTAR A REQUISIÇÃO USANDO O PROTOCOLO CORRENTE, MAS ESTARÁ PRONTO A FAZÊ-LO APÓS O CLIENTE ATUALIZAR PARA UM PROTOCOLO DIFERENTE
		428 => 'Precondition Required', // O SERVIDOR DE ORIGEM REQUER QUE A RESPOSTA SEJA CONDICIONAL
		429 => 'Too Many Requests', // O USUÁRIO ENVIOU MUITAS REQUISIÇÕES NUM DADO TEMPO (LIMITAÇÃO DE FREQUÊNCIA)
		431 => 'Request Header Fields Too Large', // O SERVIDOR NÃO QUER PROCESSAR A REQUISIÇÃO PORQUE OS CAMPOS DE CABEÇALHO SÃO MUITO GRANDES
		451 => 'Unavailable For Legal Reasons', // O USUÁRIO REQUISITOU UM RECURSO ILEGAL, TAL COMO UMA PÁGINA CENSURADA POR UM GOVERNO

		// RESPOSTAS DE ERRO DO SERVIDOR
		500 => 'Internal Server Error', // O SERVIDOR ENCONTROU UMA SITUAÇÃO COM A QUAL NÃO SABE LIDAR
		501 => 'Not Implemented', // O MÉTODO DA REQUISIÇÃO NÃO É SUPORTADO PELO SERVIDOR E NÃO PODE SER MANIPULADO
		502 => 'Bad Gateway', // O SERVIDOR, AO TRABALHAR COMO UM GATEWAY A FIM DE OBTER UMA RESPOSTA NECESSÁRIA PARA MANIPULAR A REQUISIÇÃO, OBTEVE UMA RESPOSTA INVÁLIDA
		503 => 'Service Unavailable', // O SERVIDOR NÃO ESTÁ PRONTO PARA MANIPULAR A REQUISIÇÃO
		504 => 'Gateway Timeout', // O SERVIDOR ESTÁ ATUANDO COMO UM GATEWAY E NÃO OBTÉM UMA RESPOSTA A TEMPO
		505 => 'HTTP Version Not Supported', // A VERSÃO HTTP USADA NA REQUISIÇÃO NÃO É SUPORTADA PELO SERVIDOR
		506 => 'Variant Also Negotiates', // O SERVIDOR TEM UM ERRO DE CONFIGURAÇÃO INTERNO (A NEGOCIAÇÃO TRANSPARENTE DE CONTEÚDO PARA A REQUISIÇÃO RESULTA EM UMA REFERÊNCIA CIRCULAR)
		507 => 'Insufficient Storage', // O SERVIDOR TEM UM ERRO INTERNO DE CONFIGURAÇÃO (O RECURSO VARIANTE ESCOLHIDO ESTÁ CONFIGURADO PARA ENTRAR EM NEGOCIAÇÃO TRANSPARENTE DE CONTEÚDO COM ELE MESMO, E PORTANTO, NÃO É UMA PONTA VÁLIDA NO PROCESSO DE NEGOCIAÇÃO)
		508 => 'Loop Detected', // O SERVIDOR DETECTOU UM LOOPING INFINITO AO PROCESSAR A REQUISIÇÃO
		510 => 'Not Extended', // EXIGEM-SE EXTENSÕES POSTERIORES À REQUISIÇÃO PARA O SERVIDOR ATENDÊ-LA
		511 => 'Network Authentication Required', // O CÓDIGO DE STATUS 511 INDICA QUE O CLIENTE PRECISA SE AUTENTICAR PARA GANHAR ACESSO À REDE

		default => 'Invalid Code' // INFORMOU UM CÓDIGO INVÁLIDO
	};
}
